version: "3.2"
services:
  web:
    container_name: web1
    build: .
    image: dzek69/docker-windows-notifier-test
    volumes:
      - "./test:/app"
  node:
    container_name: test2
    build: .
    image: dzek69/docker-windows-notifier-test2
    volumes:
      - "volume_not_bind:/tmp"
      - "./test2/files:/files"
      - type: bind
        source: ./test2
        target: /app
      - type: volume
        source: test_volume
        target: /test_volume
      - "/will_be_a_volume_too"

volumes:
  test_volume:
  volume_not_bind: